name: CI/CD Task

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64', 'task']

    steps:
      - uses: actions/checkout@v2

      
      - name: Upload file production.properties
        run: cp /home/ubuntu/production.properties ./src/main/resources 

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Stop old container
        run: sudo docker container stop task-container-1 || true

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Delete old container-1
        run: sudo docker container rm task-container-1 || true

      - name: Delete old image
        run: sudo docker image rm task || true

      - name: Build the Docker image
        run: sudo docker build -t task .

      - name: Run docker image for container-1
        run: sudo docker run -d -p 8080:8080 --name task-container-1 task sleep infinity || echo "success"

      - name: Check if container-1 is running
        id: check-container-1
        run: echo ::set-output name=running::$(sudo docker inspect -f '{{.State.Running}}' task-container-1)

      - name: Stop old container-2
        run: sudo docker container stop task-container-2 || true

      - name: Delete old container-2
        run: sudo docker container rm task-container-2 || true

      - name: Run docker image for container-2
        run: sudo docker run -d -p 9090:8080 --name task-container-2 task sleep infinity || echo "success"
